[project]
name = "impulse_telecom"
version = "0.1.0"
description = ""
authors = [
    {name = "Yankovskiy Georgiy",email = "admin@yageorgiy.ru"}
]
readme = "README.md"
requires-python = ">=3.11"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.2.5"
pytest-mock = "^3.14.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.2.0"
mypy = "^1.15.0"
black = "^25.1.0"
isort = "^6.0.1"
pre-commit = "^4.2.0"

[tool.mypy]
python_version = "^3.11"
strict = true
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
main = "main:main"